export class AppLabelConstants {

  // auth label Constants
  public static dashboard = "Dashboard";
  // auth label Constants
  public static signIn = "Sign In";
  public static PasswordUpdate = "Update Password";
  public static passwordRecovery = "Password Recovery";

  // Input Fields Label
  public static inputEmail = "Email address";
  public static inputNumber = "Phone Number";
  public static inputPassword = "Password";
  public static oldPassword = "Old Password";
  public static confirmPassword = "Confirm Password";
  public static firstName = "First Name";
  public static lastName = "Last Name";
  public static updateVersionToApplyPatch = "Update Version to Apply Patch";
  public static update = "Update";
  public static patchAsset = "Patch Asset";
  public static cancel = "Cancel";
  public static inputRole = "Role";
  public static additionalRole = "Additional Roles";
  public static binNumber = "BIN Number";
  public static unPatch = "Unpatched";
  public static patch = "Patched";


  //anchor Text
  public static forgotPassword = "Forgot Password?";
  public static backToLogin = "Back to login";
  public static alreadyExists = "Email already exists in the list.";

//button text
  public static login = "Login";
  public static sendEmail = "Send Email";
  public static register = "Register";
  public static resendLink = "Resend Invite";
  public static updatePassword = "Update Password";
  public static scansStatus = "Scans Status";
  public static headingCheckMail = "Check Your Email";
  public static magicLink = "This link has expired. Request for a new invite  link below"
  public static reInvitedLink = "A re-invite has been sent to your email. Click on the provided link to register"
  public static alreadyBeenRegistered = "You have already been registered."
  public static registeredUser = "Registered User."
  public static expiredLink = "Registration Link ."


  // coverage
  public static coverage = "Coverage"
  public static legitimateAlerts = "Legitimate Alerts"
  public static investigations = "Investigations"
  public static alerts = "Alerts"
  public static events = "Events"

  //In Progress Investigations Severity
  public static inProgressInvestigationsSeverity = "In Progress Investigations Severity"

  public static critical = "Critical"
  public static high = "High"
  public static medium = "Medium"
  public static low = "Low"
//Customer Intervention Required
  public static customerInterventionRequired = "Customer Intervention Required"
  public static investigationsByState = "Investigations by State"
  public static open = "Open"
  public static inProgress = "In Progress"
  public static closed = "Closed"
  public static meanTimeToDetect = "Mean Time to Detect"
  public static meanTimeToResponse = "Mean Time to Response"
  public static last24Hours = "Last 24 Hours"
  public static topAttacksBySeverity = "Top Attacks By Severity"
  // dateRange labels
  public static today = "Today"
  public static yesterday = "Yesterday"
  public static last7Days = "Last 7 Days"
  public static last30Days = "Last 30 Days"
  public static last90Days = "Last 90 Days"
  public static last1Year = "Last 1 Year"
  public static custom = "Custom"


  public static classification = "Classification"
  public static state = "State"
  public static investigationStartTime = "Investigation Start Time"
  public static investigationTitle = "Investigation Title"
  public static severity = "Severity"
  public static source = "Source"
  public static sourceType = "Source Type"
  public static assignedTo = "Assigned To"
  public static static = "State"
  public static outcome = "Outcome"
  public static investigationEndTime = "Investigation End Time"
  public static pendingInvestigations = "Pending Investigations"
  public static action = "action"
  public static bruteForceAttempt = "Brute Force Attempt"
  public static description = "Description"
  public static generatedBy = "Generated By"
  public static tags = "Tags"
  public static evidance = "Evidence"
  public static assets = "Assets"
  public static timeLine = "Timeline"
  public static notes = "Notes"
  public static indicators = "Indicators"
  public static tasks = "Tasks"
  public static companyName = "Company Name"
  public static sector = "Sector"
  public static startDate = "Start Date"
  public static subscriptionStartDate = "Subscription Start Date"
  public static subscriptionEndDate = "Subscription End Date"
  public static endDate = "End Date"
  public static accountManager = "Account Manager"
  public static status = "Status"
  public static domain = "Domain"
  public static domains = "Domains"
  public static alert = "Alert"
  public static lastUpdated = "Last Updated"
  public static socialFilter = "Sources"
  public static applyFilter = "Apply Filters"
  public static riskLevel = "Risk Level"
  public static variation = "Variation"
  public static organizationManagement = "Manage Organizations"


  public  static os = "OS"
  public  static timestamp = "Timestamp"
  public  static protocol = "Protocol"
  public  static attackerIP = "Attacker IP"
  public  static view = "View"

}
